version: "3.9"

services:
  backend:
    image: backend
    build:
      context: ./backend
    restart: always
    volumes:
      - ./static/:/vol/web/static
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0 
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db

  # frontend:
  #   image: frontend
  #   build:
  #     context: ./frontend
  #   restart: always
  #   ports:
  #     - "4200:4200"

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./database/postgres/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"

  proxy:
    image: proxy
    build:
      context: ./proxy
    restart: always
    depends_on:
      - backend
    volumes:
      - ./static/:/vol/web/static
    ports:
      - "80:8000"