version: '3.9'

services:
  backend:
    image: backend-dev
    build:
      context: ./backend
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/backend/app
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  frontend:
    image: frontend-dev
    build:
      context: ./frontend
    command: >
      sh -c "npm install && ng serve --host 0.0.0.0"
    ports: 
      - "4200:4200"
    
    depends_on: 
      - backend
  

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme