version: "3.9"

services:
  backend:
    image: wikiproduct.azurecr.io/backend
    build:
      context: ./backend
    restart: always
    volumes:
      - ./static/:/vol/web/static
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0 
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db

  frontend:
    image: wikiproduct.azurecr.io/frontend
    build:
      context: ./frontend
    restart: always
    ports:
      - "4200:4200"

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./database/postgres/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    image: wikiproduct.azurecr.io/proxy
    build:
      context: ./proxy
    restart: always
    depends_on:
      - backend
    ports:
      - "80:8000"
    volumes:
      - ./static/:/vol/web/static
