version: "3.9"

services:

  frontend:
      image: nginx
      container_name: frontend
      build:
        context: ./nginx
      ports:
        - "80:80"
      restart: always
      volumes:
        - static-data:/vol/static
      depends_on:
        - backend
      networks:
        - frontend
      links:
        - backend:backend
      

  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DJANGO_SU_NAME=${DJANGO_SU_NAME}
      - DJANGO_SU_EMAIL=${DJANGO_SU_EMAIL}
      - DJANGO_SU_PASSWORD=${DJANGO_SU_PASSWORD}
      - CHROMA_HOST_PORT=${CHROMA_HOST_PORT}
      - CHROMA_HOST_NAME=${CHROMA_HOST_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
    networks:
      - frontend
      - backend

  db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - backend
  
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    restart: always
    volumes:
      - chroma_data:/index_data 
    environment:
      - CHROMA_HOST_PORT=${CHROMA_HOST_PORT}
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  postgres-data:
  static-data:
  chroma_data: 