# Generated by Django 3.2.23 on 2024-02-01 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, db_column='Parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(db_column='Item _ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('summarized_reviews', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemBelongsTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(db_column='Category_ID', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('item', models.ForeignKey(db_column='Item _ID', on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
            options={
                'db_table': 'item_belongs_to',
                'unique_together': {('item', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ItemsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('item', models.ForeignKey(db_column='Item_ID', on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
            options={
                'db_table': 'items_history',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.PositiveSmallIntegerField()),
                ('content', models.CharField(max_length=255)),
                ('item', models.ForeignKey(db_column='Item_ID', on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.AddField(
            model_name='location',
            name='store',
            field=models.ForeignKey(db_column='Store_ID', on_delete=django.db.models.deletion.CASCADE, to='core.store'),
        ),
        migrations.AddField(
            model_name='itemshistory',
            name='store',
            field=models.ForeignKey(db_column='Store_ID', on_delete=django.db.models.deletion.CASCADE, to='core.store'),
        ),
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.ForeignKey(db_column='Item_ID', on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
        migrations.AlterUniqueTogether(
            name='itemshistory',
            unique_together={('created_on', 'item', 'store')},
        ),
    ]
