# Generated by Django 3.2.24 on 2024-02-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240202_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='url',
            new_name='map_url',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='url',
            new_name='store_url',
        ),
    ]
