# Generated by Django 3.2.24 on 2024-02-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240213_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='map_url',
            field=models.URLField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
