# Generated by Django 3.2.23 on 2024-02-02 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240201_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='item',
            field=models.ForeignKey(db_column='Item_ID', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(db_column='Item_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itembelongsto',
            name='item',
            field=models.ForeignKey(db_column='Item_ID', on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
